apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: homeassistant
  labels:
    app: mosquitto
data:
  password.txt: |
    mqtt-user:$7$101$4/rIISf6se210HHg$FXPymSiDhqsBoPvBf1se642nd3v+Rm1AsnDkqHrAig+4IJkDCTqss8J4z5zOB8eEHZTm/QGw4qKnveS+RuHKfg==
